#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Debian GNU/Linux with overlay' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-30b2743b-a32a-4596-901e-36ede1980f91' {
        load_video
        insmod gzio
        if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod ext2
        set root='hd0,gpt2'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  30b2743b-a32a-4596-901e-36ede1980f91
        else
          search --no-floppy --fs-uuid --set=root 30b2743b-a32a-4596-901e-36ede1980f91
        fi
        echo    'Loading Linux 6.1.0-10-amd64 ...'
        linux   /boot/vmlinuz-6.1.0-10-amd64 root=UUID=30b2743b-a32a-4596-901e-36ede1980f91 ro quiet boot=overlay
        echo    'Loading initial ramdisk with overlay file system ...'
        initrd  /boot/overlay.img
}
